version: '2.1'

services:
    db:
        container_name: db
        image: postgres:14
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=menufamille
        healthcheck:
          test: ["CMD-SHELL", "pg_isready"]
          interval: 10s
          timeout: 5s
          retries: 5
        logging:
          options:
            max-size: 10m
            max-file: "3"
        volumes:
          - ./db/sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
         


    web:
        container_name: web
        build:
           context: ./front
           dockerfile: web.dockerfile
        depends_on: 
          - api
        volumes:
          - ./front/menufamille:/app
          - /app/node_modules
        environment:
          - npm_config_unsafe_perm=true

    api:
        container_name: api
        build:
            context: ./api
            dockerfile: api.dockerfile
        depends_on:
            db:
              condition: service_healthy
        volumes:
          - ./api/menufamille:/app
          - pictures_candidats:/usr/src/app/cehers/upload

    proxy:
        container_name: proxy
        build:
          context: ./proxy
          dockerfile: proxy.dockerfile
        ports:
          - '80:80'
        depends_on:
          - web
          - api
        volumes:
          - ./proxy:/app


volumes:
  pictures_candidats:
